active_record_associations/college/config/routes.rb
College::Application.routes.draw do
  root 'courses#index'

  get '/courses', to: 'courses#index', as: 'courses'
  get '/courses/:id', to: 'courses#show', as: 'course'

  
end

active_record_associations/college/app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :student
end

active_record_associations/college/app/models/course.rb
class Course < ActiveRecord::Base
  has_many :enrollments
  has_many :students, through: :enrollments
end

active_record_associations/college/app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

active_record_associations/college/app/models/mentor.rb
class Mentor < ActiveRecord::Base
  has_many :students
end

active_record_associations/college/app/models/student.rb
class Student < ActiveRecord::Base
  has_one :account
  belongs_to :mentor
  has_many :enrollments
  has_many :courses, through: :enrollments
end

active_record_associations/college/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  def index
    @courses = Course.all
  end

  def show
    id = params.require(:id)
    @course = Course.find(id)
    @students = @course.students
  end
    
end

active_record_associations/college/app/helpers/courses_helper.rb
module CoursesHelper
end

active_record_associations/college/app/views/courses/index.html.erb
<h3>Courses</h3>
<ul>
<% @courses.each do |c| %>
  <li>
  <%= link_to c.name, course_path(c) %>
  </li>
<% end %>
</ul>

active_record_associations/college/app/views/courses/show.html.erb
<h4><%= @course.name %> (<%= @course.description %>)</h4>

<h5>Enrolled:</h5>
<ul>
<% @students.each do |s| %>
  <li>
  <%= s.name %> 
  </li>
<% end %>

active_record_associations/college/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>College</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>